runtime: nodejs16

env_variables: 
  DB_URI:mongodb+srv://msds:manav123@cluster0.i9g6iqa.mongodb.net/msds?retryWrites=true&w=majority
  CLOUD_NAME:dtxil2rjg
  CLOUD_API_KEY:489872418749179
  CLOUD_API_SECRET_KEY:np_MYCSn51fttpIt1FW83wnPljc
  SENDGRID_API=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
  HOST_EMAIL:ratsikumar66@gmail.com
  TO_EMAIL=info@manavsachdevdesign.com
  DOMAIN:https://msds-1.el.r.appspot.com
  GCLOUDPROJECTID:msds-1
